<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdp_InsertOp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:client="http://xmlns.oracle.com/DBFileFTPJMSIntegration_App/DBFileFTPJMSIntegration/DBFileFTPJMS_Process"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DBFileFTPJMS_Process.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmployeeDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdp_InsertOp"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DBFileFTPJMS_Process.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmployeeDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdp_InsertOp"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED SEP 17 15:14:21 IST 2025].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:EmployeeDetailsCollection>
         <xsl:for-each select="/ns0:EmployeeDetailsCollection/ns0:EmployeeDetails">
            <ns0:EmployeeDetails>
               <ns0:empId>
                  <xsl:value-of select="ns0:empId"/>
               </ns0:empId>
               <ns0:empName>
                  <xsl:value-of select="ns0:empName"/>
               </ns0:empName>
               <ns0:empStatus>
                  <xsl:value-of select="ns0:empStatus"/>
               </ns0:empStatus>
               <ns0:empDesignation>
                  <xsl:value-of select="ns0:empDesignation"/>
               </ns0:empDesignation>
               <ns0:empAddress>
                  <xsl:value-of select="ns0:empAddress"/>
               </ns0:empAddress>
               <ns0:empAge>
                  <xsl:value-of select="ns0:empAge"/>
               </ns0:empAge>
            </ns0:EmployeeDetails>
         </xsl:for-each>
      </ns0:EmployeeDetailsCollection>
   </xsl:template>
</xsl:stylesheet>
